spring:
  datasource:
    url: jdbc:h2:mem:linhadb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: "/h2"
springfox:
  documentation:
    swagger-ui:
      enabled: true
server:
  error:
    include-message: always